# Site settings
title: Mango Party
email: info@mangoparty.es
url: mangoparty.es
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "mangoparty,mango,party,zaragoza,fiesta,reggaeton,pop,hits,perreo"
skills: "Diversión - Música - Libertad"
meta_author: Jorge Cancer

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: mangoparty

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ffed65 #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: fea444 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Mango Party
  location: Location
  social: Redes Sociales
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://instagram.com/mangopartyzgz

# Postal address (add as many lines as necessary)
#address:
 # - line: 3481 Melrose Place
  #- line: Beverly Hills, CA 90210

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""

collections:
  parties:
    output: true
